### PR TITLE
Add `test_supported_features` and fix the problem introduced in #565

### PR DESCRIPTION
**Pull request by th3w1zard1**
Fixes #565

The test_supported_features test case checks if the following features of a light are legacy supported: `brightness`, `color_temp`, `color`, and `transition`. It does this by setting each feature to a known value and then checking if the component correctly supports it.

To run the test case, the `hass` object is mocked and the `_supported_features` function and `_SUPPORT_OPTS` are imported. The test case then calls the function directly, without setting up any lights or switches.

Overall, this test case ensures that the light component is correctly supporting the expected features, without relying on actual hardware or external dependencies.

This test is backwards compatible with the old `_supported_features` in the case where you'd like to revert. You shouldn't need to now that _supported_features is fixed here.

### CODE REVIEW

**Comment by th3w1zard1** [comment]
@basnijholt `test_supported_features` fails the `pre-commit` with the error:
`tests/test_switch.py:529:1: C901 'test_supported_features' is too complex (19)`

**Comment by basnijholt** [comment]
You can just add `# noqa: C901` to the line of the violation BTW to ignore the warning.

**Comment by th3w1zard1** [comment]
Whatever this error is
```
ERROR: Could not find a version that satisfies the requirement codecov==2.1.12 (from versions: none)
ERROR: No matching distribution found for codecov==2.1.12
```
is unrelated to this pr's changes. Pytest passes in the dev build.

**Comment by th3w1zard1** [comment]
> You can just add `# noqa: C901` to the line of the violation BTW to ignore the warning.

Thanks I didn't know this.

**Comment by basnijholt** [comment]
> 



> Whatever this error is
> 
> ```
> ERROR: Could not find a version that satisfies the requirement codecov==2.1.12 (from versions: none)
> ERROR: No matching distribution found for codecov==2.1.12
> ```
> 
> is unrelated to this pr's changes. Pytest passes in the dev build.

I fixed this in here https://github.com/basnijholt/adaptive-lighting/pull/573/files#diff-922ff43bbefbeb91c1a185c723fa200138c6af7601ed208a793613b01ea8d496

**Comment by basnijholt** [comment]
Sorry for being inactive here lately! I was quite distracted with other things 😄 

Have some time now though.

This looks great. I am happy you added such a comprehensive test too.

**Review by basnijholt — APPROVED** [review]

**Pull request merged**
