### PR TITLE
Add auto_reset_manual_control with async timer

### PR DESCRIPTION
**Pull request by basnijholt**
@th3w1zard1, this is an alternative way of doing it that is more async-friendly and waaaay less CPU-intensive.

### CODE REVIEW

**Comment by basnijholt** [comment]
The problem is getting the right auto reset time for the light, given a light might be in multiple switches.

**Comment by th3w1zard1** [comment]
Well this is missing the wait for transition stuff and that's the only thing I cared about. Autoreset manual control was in there solely because it was a mostly a clone of that.

Yeah, this looks great! Code looks beautiful and the class addition is a nice touch.

**Comment by basnijholt** [comment]
I just realized this might not work in the following case:
A light is marked as manually controlled, then someone changes the state of the light OUTSIDE of Home Assistant. Then the timer should reset, however, it doesn't do that now.

**Comment by th3w1zard1** [comment]
@basnijholt Do you have any ideas on how to make a test for non ha changes to lights?

**Comment by basnijholt** [comment]
Yes, we're testing that here:

https://github.com/basnijholt/adaptive-lighting/blob/1ca3bf0f6ad3c1daf403bae56cc6384b3770ebb6/tests/test_switch.py#L700-L737

The last problem is definitely solvable but requires some thinking about how to best do it.


Also, I start to get confused about how everything works exactly, which means the code is getting too complicated. I will attempt to refactor it into better-to-understand parts.

**Comment by basnijholt** [comment]
> The very last assert should be asserting manual_control=True instead it's asserting manual_control=False

That is a very good point! This should definitely be fixed.

**Comment by th3w1zard1** [comment]
@basnijholt I could commit here to update the README and strings.json for `autoreset_control_time` if you like.

**Comment by th3w1zard1** [comment]
> I just realized this might not work in the following case: A light is marked as manually controlled, then someone changes the state of the light OUTSIDE of Home Assistant. Then the timer should reset, however, it doesn't do that now.

Just checked the changes and it looks like you already fixed this by including `mark_as_manual_control` in `significant_change()`

**Comment by th3w1zard1** [comment]
@basnijholt Hello! I could update #486 to use your timer class here once this pr is merged.

**Comment by th3w1zard1** [comment]
@basnijholt This PR doesn't call `set_auto_reset_manual_control_times` when using `change_switch_settings`

**Pull request merged**
