### PR TITLE
Make sure context_id is 26 chars and partially conform to ULID standard (HA 2023.04 fix)

### PR DESCRIPTION
**Pull request by basnijholt**
Here I make sure that the context_ids are time orderable (conform the ULID standard), however, I keep the ":" chars in to identify our contexts.

We can deal with making it conform later.

### CODE REVIEW

**Comment by th3w1zard1** [comment]
I had my finger on the 'create pull request' with this exact title 😄 

You might want to check out [@bdraco's answer in that thread](https://github.com/basnijholt/adaptive-lighting/issues/493#issuecomment-1498465790) as he's one of the ha devs that introduced the change.

**Comment by th3w1zard1** [comment]
@basnijholt No you're correct! it is a simple fix for now. just change the 36 to a 26 and that'll allow enough time to come up with a better solution

**Comment by basnijholt** [comment]
I made a semi correct code now.

We partially conform the ULID standard now.

**Comment by th3w1zard1** [comment]
This is a bit beyond me, but it passes the test so who cares!

To get this working on my system I changed the 36 to a 26 and nothing else. Even that small change seemed to fix everything.

**Review by th3w1zard1 — APPROVED** [review]

**Pull request merged**
