### PR TITLE
Fix manifest issue test

### PR DESCRIPTION
**Pull request by th3w1zard1**
These are exactly the same files. I'm guessing when HACS was grabbing `manifest.json` there was some cache that was returning an old version.

### CODE REVIEW

**Comment by basnijholt** [comment]
Interesting how it merged precisely nothing 😂

**Comment by th3w1zard1** [comment]
@basnijholt Did you make a change to the way pull requests are handled? I'm seeing all sorts of new options such as 'automerge' and all tests are now showing 'required'

**Comment by th3w1zard1** [comment]
@basnijholt Also are you on discord?

**Comment by th3w1zard1** [comment]
Seeing all 5 green checkboxes is so satisfying after all the email spam I've been getting due to failed tests.

**Comment by basnijholt** [comment]
@th3w1zard1 
2A8B3EF4-8D48-42E9-A835-C8DB5E7F1E1F

So beautiful 😍

**Pull request merged**
