### PR TITLE
Release 1.9.1

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Review by th3w1zard1 — APPROVED** [review]
Well you sir are definitely running out of version numbers pretty quick before the big 'V2'. It's almost like this project's Y2K event.

**Comment by basnijholt** [comment]
Haha, there is no rule that one has to go from 1.9 to 2.0, we can just continue with 1.10.

But perhaps we should just claim "2.0" at some point 😄

**Comment by basnijholt** [comment]
I do not get why the tests are suddenly failing...

**Comment by th3w1zard1** [comment]
> I do not get why the tests are suddenly failing...

Code unnaturally breaking for no reason? That's a sign from the Code gods that it's time for a break.

**Pull request merged**
