### PR TITLE
Add max_sunrise_time and min_sunset_time overrides

### PR DESCRIPTION
**Pull request by Hypfer**
While I do quite like having my lights automatically sync with sunrise and sunset, the days can get rather short during the winter here in Germany.

Currently, there are two options to somewhat mitigate that in this custom_component:
 - The first one is specifying a static offset, which due to it being static needs regular updating as otherwise the virtual day either gets too long (early winter) or too short (mid-winter)
 - The second one is just hardcoding the sunrise and sunset time, which needs config adjustment as well as otherwise virtual days become shorter than the real ones during summer

As those are both less than ideal, this PR allows changing the virtual day to start at at most a specific time (or earlier) and also end at at least a specific time (or later). This way, the user can enjoy long summer days with synced color temperatures while also having enough virtual daylight in the winter without additional regular configuration updates.

As an example, here are the sunrise and sunset times of today
image

And here's the config with these new options
image

Utilizing the changes in this PR with the example config, the virtual sunlight duration of today is increased from 9h09m to 14h00m.

With the average person probably spending at least 8 hours or more working, I'd say that this is a huge quality of life improvement, enabling the user to do more than just work and sleep in a loop for the winter-half of the year.

This may also solve the following issues:
- #97
- #57
- https://github.com/claytonjn/hass-circadian_lighting/issues/174
- https://github.com/claytonjn/hass-circadian_lighting/issues/105

### CODE REVIEW

**Comment by basnijholt** [comment]
I have released https://github.com/basnijholt/adaptive-lighting/releases/tag/1.2.0 which includes your code 😄

**Comment by ScottG489** [comment]
Cool change! I was taking a quick look and I happened to notice a small typo [here](https://github.com/basnijholt/adaptive-lighting/pull/358/files#diff-0ca3369985a31017263d411660758bd27eae403e4e6bdda3cec2506e21690f9aR42) and [here](https://github.com/basnijholt/adaptive-lighting/pull/358/files#diff-40e7bb14b6e8145c39cf3d9f93f18686b1daf71a9159d638535505636f79d0c9R43).

> "min_sunset_time": "min_sunset_time: Manual override of the minimum sunset time, if 'None', it uses the actual sunrise time at your location (HH:MM:SS)",

I believe that last "sunrise" should be "sunset"?

**Comment by basnijholt** [comment]
You are right! Feel free to make a PR :)

**Comment by ScottG489** [comment]
Beat me to it!

**Comment by RubenKelevra** [comment]
Danke! I really enjoy this change! :)

**Comment by ACrazyConcept** [comment]
Super useful improvement. Thanks!

**Pull request merged**
