### PR TITLE
fix: lights unexpectedly turn back on after switch-off

### LINKED ISSUE #410: One light turning on again after turning off the group
#### Version information:
V1.4.1

#### Description:
On light turns back on again after turning off a group of zigbee lights (not a ZHA group but a group helper).

I get this if I listen to call_service:
Event 11 fired 9:58 AM:
event_type: call_service
data:
  domain: light
  service: turn_on
  service_data:
    entity_id: light.bedroom_light_bulb_1_level_light_color_on_off
    transition: 10
    brightness: 255
    color_temp_kelvin: 4000
origin: LOCAL
time_fired: "2022-12-22T08:58:36.535368+00:00"
context:
  id: adapt_lgt:b'*Xx`':interval:b'6%q'
  parent_id: null
  user_id: null

Event 9 fired 9:58 AM:
event_type: call_service
data:
  domain: light
  service: turn_off
  service_data:
    entity_id:
      - light.bedroom_light_bulb_1_level_light_color_on_off
      - light.bedroom_light_bulb_2_level_light_color_on_off
      - light.bedroom_light_bulb_3_level_light_color_on_off
origin: LOCAL
time_fired: "2022-12-22T08:58:31.689347+00:00"
context:
  id: 01GMWGWEBVZNCBWVF07F8S6AFR
  parent_id: 01GMWGWEBM53FTCQC1CPFV2ERG
  user_id: null

Event 8 fired 9:58 AM:

### PR DESCRIPTION
**Pull request by protyposis**
Cancel ongoing split adaptation commands when lights are turned off to avoid the delayed second half of the command to turn lights back on.

Fixes https://github.com/basnijholt/adaptive-lighting/issues/410#issuecomment-1539788096. There's still a race condition between turn-off and adaptation commands, so it doesn't entirely fix #410. It reduces the likelihood, though (I am testing it locally).

### CODE REVIEW

**Comment by protyposis** [comment]
This PR is just a proposal. I have no experience with Python, so it would be great if someone could take this over and finish it up if it makes sense. Thanks :)

**Comment by basnijholt** [comment]
LGTM!

What do you think @th3w1zard1?

**Review by basnijholt — APPROVED** [review]

**Comment by basnijholt** [comment]
@protyposis, have you properly tested this at your home and does it alleviate the problem? If so, let's merge.

**Comment by protyposis** [comment]
Just pushed a small improvement, should be fine now. I have it running since two weeks, and it has noticeably reduced the likelihood that lights unexpectedly stay on or turn back on.

**Review by basnijholt — APPROVED** [review]

**Comment by basnijholt** [comment]
@all-contributors please add @protyposis for code

**Pull request merged**
