### PR TITLE
double check the tests work on main

### PR DESCRIPTION
**Pull request by th3w1zard1**
I don't have perms to run tests manually on Github Actions.

### CODE REVIEW

**Comment by th3w1zard1** [comment]
@basnijholt hey you might want to take a look at this. Did version 1.9.0 and 1.9.1 pass the tests?

**Comment by th3w1zard1** [comment]
Quickly confirmed that adaptive-lighting 1.9.1 works on my system.

**Comment by basnijholt** [comment]
Yeah, I went back ≈20 commits on main and ran the tests with Docker. Every single commit now fails with the same error:
```
    @pytest.mark.parametrize("separate_turn_on_commands", (True, False))
    async def test_separate_turn_on_commands(hass, separate_turn_on_commands):
        """Test 'separate_turn_on_commands' argument."""
        switch, (light, *_) = await setup_lights_and_switch(
            hass, {CONF_SEPARATE_TURN_ON_COMMANDS: separate_turn_on_commands}
        )
        # We just turn sleep mode on and off which should change the
        # brightness and color. We don't test whether the number are exactly
        # what we expect because we do this in other tests already, we merely
        # check whether the brightness and color_temp change.
        context = switch.create_context("test")  # needs to be passed to update method
        brightness = light.brightness
        color_temp = light.color_temp
        await switch.sleep_mode_switch.async_turn_on()
        await switch._update_attrs_and_maybe_adapt_lights(context=context)
        await hass.async_block_till_done()

        # TODO: figure out why `light.brightness` is not updating
        attrs = hass.states.get(light.entity_id).attributes
        sleep_brightness = attrs["brightness"]
        sleep_color_temp = attrs["color_temp"]

        assert sleep_brightness != brightness
        assert sleep_color_temp != color_temp

        await switch.sleep_mode_switch.async_turn_off()
        await switch._update_attrs_and_maybe_adapt_lights(context=context)
        await hass.async_block_till_done()

        attrs = hass.states.get(light.entity_id).attributes
        brightness = attrs["brightness"]
        color_temp = attrs["color_temp"]

>       assert sleep_brightness != brightness
E       assert 3 != 3
```

**Comment by basnijholt** [comment]
Something external might have changed?

**Comment by th3w1zard1** [comment]
That is hilarious. What on earth, why is that a problem?

**Pull request closed without merging**
