### PR TITLE
feat: add different brightness ramping mechanisms

### PR DESCRIPTION
**Pull request by basnijholt**
This PR allows setting different `brightness_mode`s which determine how the brightness changes around sunrise and sunset. Here `brightness_mode` can be either `"default"` (current behavior), `"linear"`, or `"tanh"`. Additionally, when **not** using `"default"`, you can set `brightness_mode_time_dark` and `brightness_mode_time_light`.

with `brightness_mode: "linear"`:
- During **_sunset_** the brightness will start adapting constantly from `max_brightness` at `time=sunset_time - brightness_mode_time_light` to `min_brightness` at `time=sunset_time + brightness_mode_time_dark`.
- During **_sunrise_** the brightness will start adapting constantly from `min_brightness` at `time=sunrise_time - brightness_mode_time_dark` to `max_brightness` at `time=sunrise_time + brightness_mode_time_light`.

with `brightness_mode: "tanh"` it uses the smooth shape of a [hyperbolic tangent function](https://mathworld.wolfram.com/HyperbolicTangent.html):
- During **_sunset_** the brightness will start adapting from 95% of the `max_brightness` at `time=sunset_time - brightness_mode_time_light` to 5% of the `min_brightness` at `time=sunset_time + brightness_mode_time_dark`.
- During **_sunrise_** the brightness will start adapting from 5% of the `min_brightness` at `time=sunrise_time - brightness_mode_time_dark` to 95% of the `max_brightness` at `time=sunrise_time + brightness_mode_time_light`.

Closes https://github.com/basnijholt/adaptive-lighting/issues/616, https://github.com/basnijholt/adaptive-lighting/issues/437, https://github.com/basnijholt/adaptive-lighting/issues/218

### CODE REVIEW

**Comment by basnijholt** [comment]
Some code to plot the results:
```python
import numpy as np
import matplotlib.pyplot as plt
import math
from typing import Tuple

# Define the constants
SUNRISE_TIME = 6  # 6 AM
SUNSET_TIME = 18  # 6 PM
MAX_BRIGHTNESS = 1.0  # 100%
MIN_BRIGHTNESS = 0.0  # 0%
BRIGHTNESS_MODE_TIME_DARK = 1.0  # 1 hour
BRIGHTNESS_MODE_TIME_LIGHT = 1.0  # 1 hour

# Define the time range for our simulation
time_range = np.linspace(0, 24, 1000)  # From 0 to 24 hours


def lerp(x, x1, x2, y1, y2):
    """Linearly interpolate between two values."""
    return y1 + (x - x1) * (y2 - y1) / (x2 - x1)


def clamp(value: float, minimum: float, maximum: float) -> float:
    """Clamp value between minimum and maximum."""
    return max(minimum, min(value, maximum))


def find_a_b(x1: float, x2: float, y1: float, y2: float) -> Tuple[float, float]:
    """Find 'a' and 'b' for a scaled and shifted tanh function."""
    # Calculate the inverse tanh values
    z1 = math.atanh(2 * y1 - 1)
    z2 = math.atanh(2 * y2 - 1)

    # Solve the equations to find 'a' and 'b'
    a = (z2 - z1) / (x2 - x1)
    b = (x1 * z2 - x2 * z1) / (x1 - x2)

    return a, b


def scaled_tanh(
    x: float,
    a: float,
    b: float,
    y_min: float = 0.0,
    y_max: float = 1.0,
) -> float:
    """Apply a scaled and shifted tanh function to a given input."""
    return y_min + (y_max - y_min) * 0.5 * (math.tanh(a * (x - b)) + 1)


def is_closer_to_sunrise_than_sunset(time, sunrise_time, sunset_time):
    """Return True if the time is closer to sunrise than sunset."""
    return abs(time - sunrise_time) < abs(time - sunset_time)


def brightness_linear(
    time,
    sunrise_time,
    sunset_time,
    time_light,
    time_dark,
    max_brightness,
    min_brightness,
):
    """Calculate the brightness for the 'linear' mode."""
    closer_to_sunrise = is_closer_to_sunrise_than_sunset(
        time, sunrise_time, sunset_time
    )
    if closer_to_sunrise:
        brightness = lerp(
            time,
            x1=sunrise_time - time_dark,
            x2=sunrise_time + time_light,
            y1=min_brightness,
            y2=max_brightness,
        )
    else:
        brightness = lerp(
            time,
            x1=sunset_time - time_light,
            x2=sunset_time + time_dark,
            y1=max_brightness,
            y2=min_brightness,
        )
    return clamp(brightness, min_brightness, max_brightness)


def brightness_tanh(
    time,
    sunrise_time,
    sunset_time,
    time_light,
    time_dark,
    max_brightness,
    min_brightness,
):
    """Calculate the brightness for the 'tanh' mode."""
    closer_to_sunrise = is_closer_to_sunrise_than_sunset(
        time, sunrise_time, sunset_time
    )
    if closer_to_sunrise:
        a, b = find_a_b(
            x1=-time_dark,
            x2=time_light,
            y1=0.05,  # be at 5% of range at x1
            y2=0.95,  # be at 95% of range at x2
        )
        brightness = scaled_tanh(
            time - sunrise_time,
            a=a,
            b=b,
            y_min=min_brightness,
            y_max=max_brightness,
        )
    else:
        a, b = find_a_b(
            x1=-time_light,  # shifted timestamp for the start of sunset
            x2=time_dark,  # shifted timestamp for the end of sunset
            y1=0.95,  # be at 95% of range at the start of sunset
            y2=0.05,  # be at 5% of range at the end of sunset
        )
        brightness = scaled_tanh(
            time - sunset_time,
            a=a,
            b=b,
            y_min=min_brightness,
            y_max=max_brightness,
        )
    return clamp(brightness, min_brightness, max_brightness)


# Calculate the brightness for each time in the time range for both modes
brightness_linear_values = [
    brightness_linear(
        time,
        SUNRISE_TIME,
        SUNSET_TIME,
        BRIGHTNESS_MODE_TIME_LIGHT,
        BRIGHTNESS_MODE_TIME_DARK,
        MAX_BRIGHTNESS,
        MIN_BRIGHTNESS,
    )
    for time in time_range
]
brightness_tanh_values = [
    brightness_tanh(
        time,
        SUNRISE_TIME,
        SUNSET_TIME,
        BRIGHTNESS_MODE_TIME_LIGHT,
        BRIGHTNESS_MODE_TIME_DARK,
        MAX_BRIGHTNESS,
        MIN_BRIGHTNESS,
    )
    for time in time_range
]

# Plot the brightness over time for both modes
plt.figure(figsize=(10, 6))
plt.plot(time_range, brightness_linear_values, label="Linear Mode")
plt.plot(time_range, brightness_tanh_values, label="Tanh Mode")
plt.vlines(SUNRISE_TIME, 0, 1, color="r", label="Sunrise", linestyles="dashed")
plt.vlines(SUNSET_TIME, 0, 1, color="b", label="Sunset", linestyles="dashed")
plt.xlim(0, 24)
plt.xlabel("Time (hours)")
plt.ylabel("Brightness")
plt.title("Brightness over Time for Different Modes")
plt.legend()
plt.grid(True)
plt.show()
```

image

**Comment by basnijholt** [comment]
Some more examples:
image
image
image

**Comment by pacjo** [comment]
Can we have something like this for temperature too?

**Comment by basnijholt** [comment]
Yes that might be possible but I would like to make something to go between a set of custom colors or color temperatures. However, I need to think of a good interface to set it.

**Comment by pacjo** [comment]
> I need to think of a good interface to set it.

How about just allowing users to put in a specific formula and then maybe add some examples to readme (with link in the HA options menu)?

**Comment by basnijholt** [comment]
I think this will lead to a lot of trouble and confusion because the math is likely non-trivial for most folks. For example check the `tanh` derivation:
https://github.com/basnijholt/adaptive-lighting/blob/104664d3588442730f7ea9e811dd1986aca0c2e8/custom_components/adaptive_lighting/helpers.py#L19-L102

**Comment by basnijholt** [comment]
Check out this new webapp to visualize the parameters https://basnijholt.github.io/adaptive-lighting/

adaptive-lighting

https://github.com/basnijholt/adaptive-lighting/assets/6897215/68908f7d-fbf1-4991-98ce-3f2af6df996f

**Comment by funkytwig** [comment]
> Yes that might be possible but I would like to make something to go between a set of custom colors or color temperatures. However, I need to think of a good interface to set it.

Not sure if I got this correct but a while aso I was thinking it would be great if it used colour temp during the day and then RGB colours at night.  This may already be done through the sleep settings but I dont quite understand how this works (from a user POV).  I often set lights to amber at night and doing this automatialy would be really nice.

**Comment by basnijholt** [comment]
@funkytwig, that is a good suggestion and close to my plan.

I think one should be able to provide 3 or 5 RGB colors or color temperatures and it will continuously interpolate  between those colors.

**Comment by funkytwig** [comment]
@basnijholt not sure if I quite follow. My thought was something like a checkbox that if you are using temp it cross fades to night colour or another defined colour from temp. The duration of the cross fade ime not sure about but it could be the last 25 present of brightness  could be a nightcolour_percent setting. We may be getting too many settings. Makes me think of a verry old book called 'inmates are running the asylum' about UI design. https://www.oreilly.com/library/view/inmates-are-running/0672326140/. A berry interesting read. Sets out how to design mobile and web apps years before they existed.

**Comment by basnijholt** [comment]
You are right about the number of parameters/variables getting out of control, which is why I would like to keep it "simple". 

I will check out that book, thanks for the suggestion!

**Comment by funkytwig** [comment]
> The `tanh` mode is a great addition. I was wondering though where the default values for `brightness_mode_time_[dark|light]` (`900`/`3600`) come from, and why you preferred them over the defaults in the simulator app (`10800`/`1800`)?
> 
> The defaults shift the adaptation quite a bit into the night compared to the `default` mode, see screenshot below vs [#699 (comment)](https://github.com/basnijholt/adaptive-lighting/pull/699#issuecomment-1670507893).
> 
> image
> 
> I guess what I am actually asking here is if there's data that indicates a preference, physiologically.

Hi.  That was my idea.  May be worth reading this thread to understand the logic.  Basically, I wanted to be able to easily define the duration from the 100% daytime setting to the minimum % setting.  Basically, I wanted the lights to start dimming 45 mins before sunset and end dimming 435 minutes after it.  I wanted the lights to be at their dimmest for the whole time the sun was totaly set and not have lights coming back up until sun started rising.  I was finding early in the morning before the sun started rising, the lights were coming up too much for me.  So having a sunset/sunrise offset did not help.  Hope this makes sence.

**Comment by protyposis** [comment]
Thanks, that makes sense (for reference, the mentioned thread is https://github.com/basnijholt/adaptive-lighting/issues/616).

> having a sunset/sunrise offset did not help

Regarding the "too many parameters" discussion above, adding a sunrise/sunset duration parameter to the offset would fix that and simplify the two `brightness_mode_time_*` parameters down to one `sunset_sunrise_duration`. Maybe something to consider for v2 :)

**Comment by funkytwig** [comment]
> Thanks, that makes sense (for reference, the mentioned thread is #616).
> 
> > having a sunset/sunrise offset did not help
> 
> Regarding the "too many parameters" discussion above, adding a sunrise/sunset duration parameter to the offset would fix that and simplify the two `brightness_mode_time_*` parameters down to one `sunset_sunrise_duration`. Maybe something to consider for v2 :)

It simply moves the the curve.  It does not change how quickly the transition from brightest to darkest happens for a light.  Have a look at https://basnijholt.github.io/adaptive-lighting/.  This is why the devs implemented it.  Maybe they will chip in to clarify but simply changing the offsets does not do what I wanted.  This has all been implemented in the beta (and possibly in the main verison now).

**Comment by funkytwig** [comment]
PS Sorry, misread your comment.  I personally prefer absolute numbers to offsets.  They are easier (certainly for me) to get my head around.  I think the reason they opted for two parameters is because it gives more flexibility (this may not be a good thing, see 'The inmates are running the asylum' reference above,  https://www.oreilly.com/library/view/inmates-are-running/0672326140/).  I would be very happy with just a single parameter as an absolute but as I said not like offsets as much.  However, removing parameters makes migration tricky.

**Comment by basnijholt** [comment]
> Regarding the "too many parameters" discussion above, adding a sunrise/sunset duration parameter to the offset would fix that and simplify the two `brightness_mode_time_*` parameters down to one `sunset_sunrise_duration`. Maybe something to consider for v2 :)

Initially, I considered an offset too. However, this would only allow for a symmetric offset around the sunset or sunrise. To allow for asymmetric offsets, one has to  introduce yet another parameter to apply a shift in the offset, which also results in two parameters. 

Regarding the defaults, I have not given this a lot of thought at all, I only made them sufficiently different in the app to highlight that one can apply a different offset to before and after sunset/sunrise. I’m happy to change them to a perhaps more sensible default if you have a suggestion.

**Comment by protyposis** [comment]
> However, this would only allow for a symmetric offset around the sunset or sunrise. To allow for asymmetric offsets, one has to introduce yet another parameter to apply a shift in the offset, which also results in two parameters.

Hmm, I recognized this advantage of the chosen parameter design and actually wanted to configure an asymmetric curve, but it always looks symmetric to me, at least in the simulator (which is super helpful!). Here's the curve with dark/light at `3600`/`3600`:
image

Now when I configure them extremely asymmetric, e.g. `1`/`7199`, it still yields a symmetric curve:
image
(With the additional sunrise/sunset shift by one hour, the curve is exactly the same as above. Hence, sunrise + offset + duration is currently equivalent to sunrise + offset + dark + light, where the asymmetry between dark and light is just another offset to the offset.)

If your "allow for asymmetric offsets" was actually just teasing a future feature, please excuse my misunderstanding.

**Comment by TheWanderer1983** [comment]
Is it possible to have the ramping for "RGB/colour temperature over time" follow the same curve as the brightness? I would like my colour temperature to be at the highest intensity for much longer than it is.

**Pull request merged**
