### PR TITLE
add `jaraco.functools` and ignore user warnings by default

### PR DESCRIPTION
**Pull request by th3w1zard1**

### CODE REVIEW

**Comment by basnijholt** [comment]
Can you explain what added `jaraco.functools` does?

**Comment by th3w1zard1** [comment]
@basnijholt It's required for `-x/--exitfirst/maxfails=n` arguments passed to pytest. It's also required if you want to run a single test out of the `test_switch.py` file.

**Comment by basnijholt** [comment]
You can already do that, e.g.:

```
docker run -v $(pwd):/app basnijholt/adaptive-lighting:latest --show-capture=log --exitfirst -vvv tests/components/adaptive_lighting/test_switch.py::test_adaptive_lighting_switches
```
That runs one test and would also exit on the first fail (however here I just run 1 test)

**Comment by th3w1zard1** [comment]
> You can already do that, e.g.:
> 
> ```
> docker run -v $(pwd):/app basnijholt/adaptive-lighting:latest --show-capture=log --exitfirst -vvv tests/components/adaptive_lighting/test_switch.py::test_adaptive_lighting_switches
> ```
> 
> That runs one test and would also exit on the first fail (however here I just run 1 test)

Yes everytime I try that command it tells me to install jaraco?

**Comment by th3w1zard1** [comment]
```
/usr/local/lib/python3.11/site-packages/pytest_sugar.py:155: PytestDeprecationWarning: The hookimpl pytest_configure uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(trylast=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
  @pytest.mark.trylast
/usr/local/lib/python3.11/site-packages/pytest_cov/plugin.py:136: PytestDeprecationWarning: The hookimpl pytest_load_initial_conftests uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(tryfirst=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
  @pytest.mark.tryfirst
/usr/local/lib/python3.11/site-packages/pytest_aiohttp/plugin.py:21: PytestDeprecationWarning: The hookimpl pytest_configure uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(tryfirst=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
  @pytest.mark.tryfirst
============================= test session starts ==============================
platform linux -- Python 3.11.2, pytest-7.2.2, pluggy-1.0.0 -- /usr/local/bin/python3
cachedir: .pytest_cache
rootdir: /core, configfile: pyproject.toml, testpaths: tests
plugins: requests-mock-1.10.0, test-groups-1.0.3, xdist-3.2.1, socket-0.5.1, sugar-0.9.6, syrupy-4.0.0, cov-3.0.0, pytest_freezer-0.4.6, aiohttp-1.0.4, picked-0.4.6, anyio-3.6.2, asyncio-0.20.3, timeout-2.1.0, respx-0.20.1, unordered-0.5.2
asyncio: mode=Mode.AUTO
timeout: 9.0s
timeout method: signal
timeout func_only: False
collecting ... /usr/local/lib/python3.11/site-packages/coverage/inorout.py:507: CoverageWarning: Module 'homeassistant' was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
/usr/local/lib/python3.11/site-packages/coverage/control.py:858: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
/usr/local/lib/python3.11/site-packages/pytest_cov/plugin.py:308: CovReportWarning: Failed to generate report: No data to report.

  warnings.warn(CovReportWarning(message))
collected 0 items / 1 error
WARNING: Failed to generate report: No data to report.


==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1206: in _gcd_import
    ???
<frozen importlib._bootstrap>:1178: in _find_and_load
    ???
<frozen importlib._bootstrap>:1149: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
/usr/local/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
tests/components/abode/conftest.py:5: in <module>
    from jaraco.abode.helpers import urls as URL
E   ModuleNotFoundError: No module named 'jaraco'
=============================== warnings summary ===============================
../usr/local/lib/python3.11/site-packages/pytest_cov/plugin.py:256
  /usr/local/lib/python3.11/site-packages/pytest_cov/plugin.py:256: PytestDeprecationWarning: The hookimpl CovPlugin.pytest_configure_node uses old-style configuration options (marks or attributes).
  Please use the pytest.hookimpl(optionalhook=True) decorator instead
   to configure the hooks.
   See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
    def pytest_configure_node(self, node):

../usr/local/lib/python3.11/site-packages/pytest_cov/plugin.py:265
  /usr/local/lib/python3.11/site-packages/pytest_cov/plugin.py:265: PytestDeprecationWarning: The hookimpl CovPlugin.pytest_testnodedown uses old-style configuration options (marks or attributes).
  Please use the pytest.hookimpl(optionalhook=True) decorator instead
   to configure the hooks.
   See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
    def pytest_testnodedown(self, node, error):

<frozen abc>:106
  <frozen abc>:106: DeprecationWarning: Inheritance class HomeAssistantApplication from web.Application is discouraged

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.11.2-final-0 -----------

--------------------------- snapshot report summary ----------------------------

=========================== short test summary info ============================
ERROR  - ModuleNotFoundError: No module named 'jaraco'
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 3 warnings, 1 error in 0.22s =========================
```

**Comment by basnijholt** [comment]
That is very strange! Especially since I do not run into that error and that it doesn't happen in the CI.

If anything, we need:
```patch
diff --git a/test_dependencies.py b/test_dependencies.py
index a4dc0e8..efa3e07 100644
--- a/test_dependencies.py
+++ b/test_dependencies.py
@@ -20,6 +20,7 @@ for i, line in enumerate(lines):

 required = [
     "components.recorder",
+    "components.abode",
     "components.mqtt",
     "components.zeroconf",
     "components.http",
```

**Comment by th3w1zard1** [comment]
Looks like your command worked actually! I'm unsure what I tried that day as it looks like I forgot to include the command in the logs. Thank you!

**Pull request closed without merging**
