### PR TITLE
Test multiple Home Assistant releases and the dev branch

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by basnijholt** [comment]
@th3w1zard1, interestingly this new workflow *already* highlights that we broke something for older HA versions!

**Comment by th3w1zard1** [comment]
@basnijholt I'm happy it does.

A lot of it _shouldn't_ pass, they just happened to pass consistently during the test phase. so it became my guideline for the order of operation.

I noticed when `assert` failed usually fired off errors such as the ones in the pytest listed here. Although none of those seem to be related to the `test_state_change_handlers` code I wrote, as it looks like it's erroring in the setup stage?

I ended up using `raise ValueError()` during testing as it usually pinpointed the line when `assert` wouldn't.

**Comment by th3w1zard1** [comment]
Could it be related to the python version each core is running?

**Comment by th3w1zard1** [comment]
It's possible we still have the runaway timer issue present in 1.10.0. `_AsyncSingleShotTimer` never calls the `reset()` function we pass as an argument.

**Comment by th3w1zard1** [comment]
How does one test this PR on their own system?

**Comment by th3w1zard1** [comment]
Logs make no sense, none are even close to the hundreds I saw when writing that test.

**Comment by th3w1zard1** [comment]
I'm 99% sure it's the test itself that generates the error and nothing a user will see on their side. We still use a few unsafe methods to run that test. But it's very odd that it's failing in the setup stage??

**Comment by th3w1zard1** [comment]
I'm 100% sure it's the test now.
```
ERROR:homeassistant:Error doing job: Exception in callback _async_track_state_added_domain.<locals>._async_state_change_dispatcher(<Event state_...brightness=50>) at /home/runner/work/adaptive-lighting/adaptive-lighting/core/homeassistant/helpers/event.py:465:   File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
```

this is directly due to using `async_set` to change the brightness and bypass hass's state_changed event.

**Comment by th3w1zard1** [comment]
It occured to me we no longer need to use `async_set` as I already removed the other examples. What was I thinking.

I removed it and committed the change here.

**Comment by th3w1zard1** [comment]
@basnijholt it should work correctly on all versions of hass core now. Could you run the test again please?

**Comment by basnijholt** [comment]
OK great! So I should revert https://github.com/basnijholt/adaptive-lighting/pull/552/commits/8d01b6ec4ea8b97feb8dabf8b737be604755dffd

**Comment by th3w1zard1** [comment]
Looks like it's fixed
image

**Comment by basnijholt** [comment]
Great! I reverted.

This simple change is pretty cool and useful I think 😄

**Pull request merged**
